### ISSUE TITLE
can't use with django 1.10

### ISSUE THREAD

**Issue by mmodenesi** [and3rson/django-searchable-select#1]
```
File "[...edited...] /site-packages/searchableselect/widgets.py", line 2, in <module>
from django.db.models.loading import get_model

ImportError: No module named 'django.db.models.loading'
```

After fixing this import following [this approach](https://github.com/omab/django-social-auth/issues/842), other import errors will appair. Apparently many things moved arround in Django.

**Comment by and3rson** [comment]
@mmodenesi Thanks for the report!

I've just fixed everything in master. I also included an example project just in case someone wants to see it in action before using. I should definitely have some tests for everything. For now things are working on Django `1.10` and preserving backwards compatibility until at least `1.8`.

The latest version is now `1.4.1` and is available on [pypi](https://pypi.python.org/pypi/django-searchable-select/1.4.1).

In case there are still any problems, let me know and I'll reopen this issue.
I'm glad this small lib still helps people.
