### ISSUE TITLE
some fields have no value so only blue rectangle is displayed

### ISSUE THREAD

**Issue by shalakhin** [and3rson/django-searchable-select#13]

**Comment by notsoluckycharm** [comment]
I don't know if you figured this out, but your model must return `name` or override the default template to use your required field. As coded, you can't specify the display field right now unfortunately :(

**Comment by shalakhin** [comment]
I noticed that too. Fix this as soon as find time

**Comment by and3rson** [comment]
Hey!
Sorry for the huge delay. I've recently been busy with a lot of other stuff.
The project is currently looking for maintainers.
Please open a issue if you are willing to contribute some time to this.
Thanks!

**Comment by and3rson** [comment]
Thanks for reporting, this is now fixed
