### ISSUE TITLE
A maximum of 5 selections are listed for a foreign key.

### ISSUE THREAD

**Issue by konohitowa** [and3rson/django-searchable-select#3]
Although views.filter_models limits the result to 10 items, only 5 show up in the selection. I've changed the array slice from 10 to 30 items (for example) but still only see 5. I added a print() statement to verify that I'm actually retrieving more than 5 items in filter_models.

My assumption is that there's a limit somewhere within JQuery or elsewhere but I don't know where it is/can't find it.

It would be better if there were a parameter to limit the results rather than the hard coded array slice value, especially since there seems to be another limit elsewhere.

Django 1.10.5
Problem occurs in both Safari 10.0.3 and Chrome 56.0.2924.87 (64-bit) on macOS 10.12.3.

NOTE: This is for a foreign key (with ~76k rows).

**Comment by and3rson** [comment]
@konohitowa Thanks for the report! I've added a `limit` argument to the field constructor that is also respected by a Typeahead dropdown. Fixed in version 1.4.4-2.
Check out the readme for this.

**Comment by konohitowa** [comment]
Awesome turnaround. I think you still need a typecast in views.filter_models like this:

    limit = int(request.GET.get('limit', 10))


Thanks. This is an invaluable plugin for me!

**Comment by and3rson** [comment]
That's right, I noticed this missing typecast right after I've built 1.4.4-2. Try 1.4.4-3.

I'm glad it helps :)
