### ISSUE TITLE
AttributeError: type object 'MyModel' has no attribute 'split'

### ISSUE THREAD

**Issue by marrip** [and3rson/django-searchable-select#33]
Hey, I am not sure if I misunderstood the docs but when I add `widgets = {'myfield': SearchableSelect(model='MyModel', search_field='myfield', many=True, limit=10)}` to my form it throws this error. Any pointers would be highly appreciated 😄

**Comment by marrip** [comment]
Found the error...it wasn't a string...sorry

**Comment by PanchoG17** [comment]
what was your solution? i have the same issue

**Comment by marrip** [comment]
Sorry for getting back to you so late. I looked at my code - honestly it was a while ago I worked with this so I am not completely sure. But I think the `'myfield': SearchableSelect(...)` needs to be a in double quotes like so `"myfield"`. Never got this component to work the way I wanted though. 😓
