### ISSUE TITLE
support multiple search fields

### ISSUE THREAD

**Issue by shalakhin** [and3rson/django-searchable-select#9]
@and3rson I think it would be great if

```python
widgets = {
    'user': SearchableSelect(model='users.User',
                             search_field='email',
                             many=False, limit=10),
}
```

will be

```python
widgets = {
    'user': SearchableSelect(model='users.User',
                             search_field=['email', 'first_name', 'last_name'],
                             many=False, limit=10),
}
```

If you agree I will make it.

**Comment by and3rson** [comment]
@shalakhin That's a great idea! We can definitely have it.
Also, don't forget to keep it backward-compatible with single string.

**Comment by shalakhin** [comment]
Sure thing I won’t forget about compatibility

**Comment by and3rson** [comment]
@shalakhin seems like this can be done within the scope #10, I'll probably close this issue in favor of #10.
